import { GetParametersByPathCommand, SSMClient } from "@aws-sdk/client-ssm";
import type { GetParametersByPathCommandOutput } from "@aws-sdk/client-ssm";

/**
 * Configuration that is not in the environment.
 *
 * Amplify's *Secret management* does not create environment variables. It
 * creates AWS Systems Manager Parameter Store entries, and a Next.js server
 * never sees them under their own names — which is why an app can read
 * `process.env.COGNITO_CLIENT_ID` on a deployment whose console shows that
 * secret plainly present, and get nothing.
 *
 * The alternative to reading them here is to have the build write them into
 * `.env.production`, which works and is what AWS documents, but puts every
 * secret into a deployment artifact that anyone who can read the deployment can
 * read. This module takes the other path: the values stay in Parameter Store,
 * encrypted, and are fetched at runtime with the credentials of the app's SSR
 * compute role. Nothing sensitive is ever written to disk or into a build.
 *
 * Secrets scoped to "all branches" in the console live under
 * `/amplify/shared/<app id>/<name>`. Branch-scoped secrets live under
 * `/amplify/<app id>/<branch>-branch-<hash>/<name>`, where the hash is
 * generated by Amplify and is not derivable from anything the runtime knows —
 * so this reads the shared path, and branch scope is not supported. That is a
 * deliberate limit, not an oversight: shared scope is the only one whose path a
 * running app can construct.
 */

/** Where "all branches" secrets live, given an app id. */
function sharedPath(appId: string): string {
	return `/amplify/shared/${appId}/`;
}

/** How long a good result is trusted before Parameter Store is asked again. */
const SUCCESS_TTL_MS = 10 * 60 * 1000;

/**
 * How long a failure is remembered.
 *
 * Much shorter than a success. A throttle or a transient network error should
 * cost one slow request and then recover, rather than wedging sign-in until the
 * container happens to recycle.
 */
const FAILURE_TTL_MS = 30 * 1000;

/** What a load attempt produced. */
export type SecretLoad = {
	/** Secret name to value. Empty when none were read. */
	values: Record<string, string>,
	/** The path consulted, for diagnostics. Null when no app id was known. */
	path: string | null,
	/**
	 * Why nothing was loaded, if that is the case. A message, never a value.
	 * Null means the load succeeded, including succeeding with nothing to read.
	 */
	error: string | null,
}

type CacheEntry = {
	loadedAt: number,
	load: SecretLoad,
}

/*
	Module scope, so a warm Lambda container reuses what it already fetched. A
	promise rather than a value, so that concurrent requests during a cold start
	collapse into a single Parameter Store call instead of one per request.
*/
let inFlight: Promise<SecretLoad> | null = null;
let cached: CacheEntry | null = null;
let client: SSMClient | null = null;

/**
 * The Amplify app id, or an empty string when this is not an Amplify runtime.
 *
 * Amplify sets AWS_APP_ID in the build environment. Whether it reaches the SSR
 * runtime is not documented, so the build spec forwards it explicitly and
 * AMPLIFY_APP_ID is honored as an override. An app id is not a secret — it is
 * the subdomain of the app's own URL.
 */
export function amplifyAppId(): string {
	return (process.env.AMPLIFY_APP_ID ?? process.env.AWS_APP_ID ?? "").trim();
}

/**
 * Fetches every secret under the shared path.
 *
 * @param appId The Amplify app id
 * @returns The values read
 */
async function fetchSecrets(appId: string): Promise<Record<string, string>> {
	client ??= new SSMClient({});

	const path = sharedPath(appId);
	const values: Record<string, string> = {};
	let nextToken: string | undefined = undefined;

	// Paginated because Parameter Store returns at most 10 per call, and an app
	// can hold more secrets than that.
	do {
		const response: GetParametersByPathCommandOutput = await client.send(new GetParametersByPathCommand({
			Path: path,
			WithDecryption: true,
			MaxResults: 10,
			NextToken: nextToken,
		}));

		for (const parameter of response.Parameters ?? []) {
			// Names come back as full paths; the secret's name is the last segment.
			const name = (parameter.Name ?? "").split("/").pop();

			if (name && typeof parameter.Value === "string") {
				values[name] = parameter.Value;
			}
		}

		nextToken = response.NextToken;
	} while (nextToken);

	return values;
}

/**
 * Loads the secrets, from cache when it is fresh.
 *
 * Never throws and never logs a value. A failure here must not take the site
 * down: every caller treats an empty result the same way it treats an
 * unconfigured environment, which degrades to "no sign-in method" rather than a
 * 500. The reason is kept for the diagnostics route to report.
 *
 * @returns What was loaded, and why not if nothing was
 */
export function loadSecrets(): Promise<SecretLoad> {
	const now = Date.now();

	if (cached) {
		const ttl = cached.load.error ? FAILURE_TTL_MS : SUCCESS_TTL_MS;

		if (now - cached.loadedAt < ttl) {
			return Promise.resolve(cached.load);
		}
	}

	// A refresh is due, but an in-flight fetch is already producing one.
	if (inFlight) {
		return inFlight;
	}

	const appId = amplifyAppId();

	if (!appId) {
		// Not an Amplify runtime. Local development gets everything from the
		// environment, so this is the ordinary case and not an error.
		const load: SecretLoad = { values: {}, path: null, error: null };
		cached = { loadedAt: now, load };
		return Promise.resolve(load);
	}

	inFlight = fetchSecrets(appId)
		.then((values): SecretLoad => ({ values, path: sharedPath(appId), error: null }))
		.catch((cause: unknown): SecretLoad => ({
			values: {},
			path: sharedPath(appId),
			// The message only. An SSM error names the parameter path and the
			// principal, which is useful, but the object can carry more.
			error: cause instanceof Error ? cause.message : "Unknown error reading Parameter Store",
		}))
		.then((load) => {
			cached = { loadedAt: Date.now(), load };
			inFlight = null;
			return load;
		});

	return inFlight;
}

/**
 * Forgets everything cached. For tests.
 */
export function resetSecretCache(): void {
	cached = null;
	inFlight = null;
	client = null;
}
